category = [['Active Life', 'Amateur Sports Teams'], 
['Active Life', 'Amusement Parks'], 
['Active Life', 'Aquariums'], 
['Active Life', 'Archery'], 
['Active Life', 'Badminton'], 
['Active Life', 'Basketball Courts'], 
['Active Life', 'Beaches'], 
['Active Life', 'Bike Rentals'], 
['Active Life', 'Boating'], 
['Active Life', 'Bowling'], 
['Active Life', 'Challenge Courses'], 
['Active Life', 'Climbing'], 
['Active Life', 'Cycling Classes'], 
['Active Life', 'Disc Golf'], 
['Active Life', 'Diving'], 
['Active Life', 'Diving', 'Free Diving'], 
['Active Life', 'Diving', 'Scuba Diving'], 
['Active Life', 'Fishing'], 
['Active Life', 'Fitness & Instruction'], 
['Active Life', 'Fitness & Instruction', 'Barre Classes'], 
['Active Life', 'Fitness & Instruction', 'Boot Camps'], 
['Active Life', 'Fitness & Instruction', 'Boxing'], 
['Active Life', 'Fitness & Instruction', 'Dance Studios'], 
['Active Life', 'Fitness & Instruction', 'Gyms'], 
['Active Life', 'Fitness & Instruction', 'Martial Arts'], 
['Active Life', 'Fitness & Instruction', 'Meditation Centers'], 
['Active Life', 'Fitness & Instruction', 'Pilates'], 
['Active Life', 'Fitness & Instruction', 'Swimming Lessons/Schools'], 
['Active Life', 'Fitness & Instruction', 'Tai Chi'], 
['Active Life', 'Fitness & Instruction', 'Trainers'], 
['Active Life', 'Fitness & Instruction', 'Yoga'], 
['Active Life', 'Go Karts'], 
['Active Life', 'Golf'], 
['Active Life', 'Gun/Rifle Ranges'], 
['Active Life', 'Gymnastics'], 
['Active Life', 'Hang Gliding'], 
['Active Life', 'Hiking'], 
['Active Life', 'Horse Racing'], 
['Active Life', 'Horseback Riding'], 
['Active Life', 'Hot Air Balloons'], 
['Active Life', 'Kiteboarding'], 
['Active Life', 'Lakes'], 
['Active Life', 'Laser Tag'], 
['Active Life', 'Leisure Centers'], 
['Active Life', 'Mini Golf'], 
['Active Life', 'Mountain Biking'], 
['Active Life', 'Paddleboarding'], 
['Active Life', 'Paintball'], 
['Active Life', 'Parks'], 
['Active Life', 'Parks', 'Dog Parks'], 
['Active Life', 'Parks', 'Skate Parks'], 
['Active Life', 'Playgrounds'], 
['Active Life', 'Rafting/Kayaking'], 
['Active Life', 'Recreation Centers'], 
['Active Life', 'Rock Climbing'], 
['Active Life', 'Skating Rinks'], 
['Active Life', 'Skydiving'], 
['Active Life', 'Sledding'], 
['Active Life', 'Soccer'], 
['Active Life', 'Sports Clubs'], 
['Active Life', 'Squash'], 
['Active Life', 'Summer Camps'], 
['Active Life', 'Surfing'], 
['Active Life', 'Swimming Pools'], 
['Active Life', 'Tennis'], 
['Active Life', 'Trampoline Parks'], 
['Active Life', 'Tubing'], 
['Active Life', 'Zoos'], 
['Arts & Entertainment', 'Arcades'], 
['Arts & Entertainment', 'Art Galleries'], 
['Arts & Entertainment', 'Botanical Gardens'], 
['Arts & Entertainment', 'Casinos'], 
['Arts & Entertainment', 'Cinema'], 
['Arts & Entertainment', 'Cultural Center'], 
['Arts & Entertainment', 'Festivals'], 
['Arts & Entertainment', 'Jazz & Blues'], 
['Arts & Entertainment', 'Museums'], 
['Arts & Entertainment', 'Music Venues'], 
['Arts & Entertainment', 'Opera & Ballet'], 
['Arts & Entertainment', 'Performing Arts'], 
['Arts & Entertainment', 'Professional Sports Teams'], 
['Arts & Entertainment', 'Psychics & Astrologers'], 
['Arts & Entertainment', 'Race Tracks'], 
['Arts & Entertainment', 'Social Clubs'], 
['Arts & Entertainment', 'Stadiums & Arenas'], 
['Arts & Entertainment', 'Ticket Sales'], 
['Arts & Entertainment', 'Wineries'], 
['Automotive', 'Aircraft Dealers'], 
['Automotive', 'Auto Customization'], 
['Automotive', 'Auto Detailing'], 
['Automotive', 'Auto Glass Services'], 
['Automotive', 'Auto Loan Providers'], 
['Automotive', 'Auto Parts & Supplies'], 
['Automotive', 'Auto Repair'], 
['Automotive', 'Boat Dealers'], 
['Automotive', 'Body Shops'], 
['Automotive', 'Car Dealers'], 
['Automotive', 'Car Stereo Installation'], 
['Automotive', 'Car Wash'], 
['Automotive', 'Gas & Service Stations'], 
['Automotive', 'Motorcycle Dealers'], 
['Automotive', 'Motorcycle Repair'], 
['Automotive', 'Oil Change Stations'], 
['Automotive', 'Parking'], 
['Automotive', 'RV Dealers'], 
['Automotive', 'Registration Services'], 
['Automotive', 'Smog Check Stations'], 
['Automotive', 'Tires'], 
['Automotive', 'Towing'], 
['Automotive', 'Truck Rental'], 
['Automotive', 'Wheel & Rim Repair'], 
['Automotive', 'Windshield Installation & Repair'], 
['Beauty & Spas', 'Barbers'], 
['Beauty & Spas', 'Cosmetics & Beauty Supply'], 
['Beauty & Spas', 'Day Spas'], 
['Beauty & Spas', 'Eyelash Service'], 
['Beauty & Spas', 'Hair Extensions'], 
['Beauty & Spas', 'Hair Removal'], 
['Beauty & Spas', 'Hair Removal', 'Laser Hair Removal'], 
['Beauty & Spas', 'Hair Salons'], 
['Beauty & Spas', 'Hair Salons', 'Blow Dry/Out Services'], 
['Beauty & Spas', 'Hair Salons', 'Hair Extensions'], 
['Beauty & Spas', 'Hair Salons', 'Hair Stylists'], 
['Beauty & Spas', 'Hair Salons', "Men's Hair Salons"], 
['Beauty & Spas', 'Makeup Artists'], 
['Beauty & Spas', 'Massage'], 
['Beauty & Spas', 'Medical Spas'], 
['Beauty & Spas', 'Nail Salons'], 
['Beauty & Spas', 'Permanent Makeup'], 
['Beauty & Spas', 'Piercing'], 
['Beauty & Spas', 'Rolfing'], 
['Beauty & Spas', 'Skin Care'], 
['Beauty & Spas', 'Tanning'], 
['Beauty & Spas', 'Tanning', 'Spray Tanning'], 
['Beauty & Spas', 'Tanning', 'Tanning Beds'], 
['Beauty & Spas', 'Tattoo'], 
['Education', 'Adult Education'], 
['Education', 'College Counseling'], 
['Education', 'Colleges & Universities'], 
['Education', 'Educational Services'], 
['Education', 'Elementary Schools'], 
['Education', 'Middle Schools & High Schools'], 
['Education', 'Preschools'], 
['Education', 'Private Tutors'], 
['Education', 'Religious Schools'], 
['Education', 'Special Education'], 
['Education', 'Specialty Schools'], 
['Education', 'Specialty Schools', 'Art Schools'], 
['Education', 'Specialty Schools', 'CPR Classes'], 
['Education', 'Specialty Schools', 'Cooking Schools'], 
['Education', 'Specialty Schools', 'Cosmetology Schools'], 
['Education', 'Specialty Schools', 'Dance Schools'], 
['Education', 'Specialty Schools', 'Driving Schools'], 
['Education', 'Specialty Schools', 'First Aid Classes'], 
['Education', 'Specialty Schools', 'Flight Instruction'], 
['Education', 'Specialty Schools', 'Food Safety Training'], 
['Education', 'Specialty Schools', 'Language Schools'], 
['Education', 'Specialty Schools', 'Massage Schools'], 
['Education', 'Specialty Schools', 'Swimming Lessons/Schools'], 
['Education', 'Specialty Schools', 'Vocational & Technical School'], 
['Education', 'Test Preparation'], 
['Education', 'Tutoring Centers'], 
['Event Planning & Services', 'Bartenders'], 
['Event Planning & Services', 'Boat Charters'], 
['Event Planning & Services', 'Cards & Stationery'], 
['Event Planning & Services', 'Caterers'], 
['Event Planning & Services', 'Clowns'], 
['Event Planning & Services', 'DJs'], 
['Event Planning & Services', 'Hotels'], 
['Event Planning & Services', 'Magicians'], 
['Event Planning & Services', 'Musicians'], 
['Event Planning & Services', 'Officiants'], 
['Event Planning & Services', 'Party & Event Planning'], 
['Event Planning & Services', 'Party Bus Rentals'], 
['Event Planning & Services', 'Party Equipment Rentals'], 
['Event Planning & Services', 'Party Supplies'], 
['Event Planning & Services', 'Personal Chefs'], 
['Event Planning & Services', 'Photographers'], 
['Event Planning & Services', 'Photographers', 'Event Photography'], 
['Event Planning & Services', 'Photographers', 'Session Photography'], 
['Event Planning & Services', 'Venues & Event Spaces'], 
['Event Planning & Services', 'Videographers'], 
['Event Planning & Services', 'Wedding Planning'], 
['Financial Services', 'Banks & Credit Unions'], 
['Financial Services', 'Banks & Credit Unions', 'heck Cashing/Pay-day Loans'], 
['Financial Services', 'Financial Advising'], 
['Financial Services', 'Insurance'], 
['Financial Services', 'Investing'], 
['Financial Services', 'Tax Services'], 
['Food', 'Bagels'], 
['Food', 'Bakeries'], 
['Food', 'Beer, Wine & Spirits'], 
['Food', 'Breweries'], 
['Food', 'Bubble Tea'], 
['Food', 'Butcher'], 
['Food', 'CSA'], 
['Food', 'Coffee & Tea'], 
['Food', 'Convenience Stores'], 
['Food', 'Cupcakes'], 
['Food', 'Desserts'], 
['Food', 'Desserts', 'heck Cashing/Pay-day Loans'], 
['Food', 'Donuts'], 
['Food', 'Farmers Market'], 
['Food', 'Food Delivery Services'], 
['Food', 'Food Trucks'], 
['Food', 'Gelato'], 
['Food', 'Grocery'], 
['Food', 'Ice Cream & Frozen Yogurt'], 
['Food', 'Internet Cafes'], 
['Food', 'Juice Bars & Smoothies'], 
['Food', 'Pretzels'], 
['Food', 'Shaved Ice'], 
['Food', 'Specialty Food'], 
['Food', 'Specialty Food', 'Candy Stores'], 
['Food', 'Specialty Food', 'Cheese Shops'], 
['Food', 'Specialty Food', 'Chocolatiers & Shops'], 
['Food', 'Specialty Food', 'Ethnic Food'], 
['Food', 'Specialty Food', 'Fruits & Veggies'], 
['Food', 'Specialty Food', 'Health Markets'], 
['Food', 'Specialty Food', 'Herbs & Spices'], 
['Food', 'Specialty Food', 'Meat Shops'], 
['Food', 'Specialty Food', 'Seafood Markets'], 
['Food', 'Street Vendors'], 
['Food', 'Tea Rooms'], 
['Food', 'Wineries'], 
['Health & Medical', 'Acupuncture'], 
['Health & Medical', 'Cannabis Clinics'], 
['Health & Medical', 'Chiropractors'], 
['Health & Medical', 'Counseling & Mental Health'], 
['Health & Medical', 'Dentists'], 
['Health & Medical', 'Dentists', 'Cosmetic Dentists'], 
['Health & Medical', 'Dentists', 'Endodontists'], 
['Health & Medical', 'Dentists', 'General Dentistry'], 
['Health & Medical', 'Dentists', 'Oral Surgeons'], 
['Health & Medical', 'Dentists', 'Orthodontists'], 
['Health & Medical', 'Dentists', 'Pediatric Dentists'], 
['Health & Medical', 'Dentists', 'Periodontists'], 
['Health & Medical', 'Diagnostic Services'], 
['Health & Medical', 'Diagnostic Services', 'Diagnostic Imaging'], 
['Health & Medical', 'Diagnostic Services', 'Laboratory Testing'], 
['Health & Medical', 'Doctors'], 
['Health & Medical', 'Doctors', 'Allergists'], 
['Health & Medical', 'Doctors', 'Anesthesiologists'], 
['Health & Medical', 'Doctors', 'Audiologist'], 
['Health & Medical', 'Doctors', 'Cardiologists'], 
['Health & Medical', 'Doctors', 'Cosmetic Surgeons'], 
['Health & Medical', 'Doctors', 'Dermatologists'], 
['Health & Medical', 'Doctors', 'Ear Nose & Throat'], 
['Health & Medical', 'Doctors', 'Family Practice'], 
['Health & Medical', 'Doctors', 'Fertility'], 
['Health & Medical', 'Doctors', 'Gastroenterologist'], 
['Health & Medical', 'Doctors', 'Gerontologists'], 
['Health & Medical', 'Doctors', 'Internal Medicine'], 
['Health & Medical', 'Doctors', 'Naturopathic/Holistic'], 
['Health & Medical', 'Doctors', 'Neurologist'], 
['Health & Medical', 'Doctors', 'Obstetricians & Gynecologists'], 
['Health & Medical', 'Doctors', 'Oncologist'], 
['Health & Medical', 'Doctors', 'Ophthalmologists'], 
['Health & Medical', 'Doctors', 'Orthopedists'], 
['Health & Medical', 'Doctors', 'Osteopathic Physicians'], 
['Health & Medical', 'Doctors', 'Pediatricians'], 
['Health & Medical', 'Doctors', 'Podiatrists'], 
['Health & Medical', 'Doctors', 'Proctologists'], 
['Health & Medical', 'Doctors', 'Psychiatrists'], 
['Health & Medical', 'Doctors', 'Pulmonologist'], 
['Health & Medical', 'Doctors', 'Sports Medicine'], 
['Health & Medical', 'Doctors', 'Tattoo Removal'], 
['Health & Medical', 'Doctors', 'Urologists'], 
['Health & Medical', 'Doulas'], 
['Health & Medical', 'Hearing Aid Providers'], 
['Health & Medical', 'Home Health Care'], 
['Health & Medical', 'Hospice'], 
['Health & Medical', 'Hospitals'], 
['Health & Medical', 'Hypnosis/Hypnotherapy'], 
['Health & Medical', 'Lactation Services'], 
['Health & Medical', 'Laser Eye Surgery/Lasik'], 
['Health & Medical', 'Massage Therapy'], 
['Health & Medical', 'Medical Centers'], 
['Health & Medical', 'Medical Spas'], 
['Health & Medical', 'Medical Transportation'], 
['Health & Medical', 'Midwives'], 
['Health & Medical', 'Nutritionists'], 
['Health & Medical', 'Occupational Therapy'], 
['Health & Medical', 'Optometrists'], 
['Health & Medical', 'Physical Therapy'], 
['Health & Medical', 'Reflexology'], 
['Health & Medical', 'Rehabilitation Center'], 
['Health & Medical', 'Retirement Homes'], 
['Health & Medical', 'Speech Therapists'], 
['Health & Medical', 'Traditional Chinese Medicine'], 
['Health & Medical', 'Urgent Care'], 
['Health & Medical', 'Weight Loss Centers'], 
['Home Services', 'Building Supplies'], 
['Home Services', 'Carpet Installation'], 
['Home Services', 'Carpeting'], 
['Home Services', 'Chimney Sweeps'], 
['Home Services', 'Contractors'], 
['Home Services', 'Damage Restoration'], 
['Home Services', 'Door Sales/Installation'], 
['Home Services', 'Electricians'], 
['Home Services', 'Fences & Gates'], 
['Home Services', 'Flooring'], 
['Home Services', 'Garage Door Services'], 
['Home Services', 'Gardeners'], 
['Home Services', 'Glass & Mirrors'], 
['Home Services', 'Gutter Services'], 
['Home Services', 'Handyman'], 
['Home Services', 'Heating & Air Conditioning/HVAC'], 
['Home Services', 'Home Cleaning'], 
['Home Services', 'Home Inspectors'], 
['Home Services', 'Home Organization'], 
['Home Services', 'Home Theatre Installation'], 
['Home Services', 'Home Window Tinting'], 
['Home Services', 'Interior Design'], 
['Home Services', 'Internet Service Providers'], 
['Home Services', 'Irrigation'], 
['Home Services', 'Keys & Locksmiths'], 
['Home Services', 'Landscape Architects'], 
['Home Services', 'Landscaping'], 
['Home Services', 'Lighting Fixtures & Equipment'], 
['Home Services', 'Masonry/Concrete'], 
['Home Services', 'Movers'], 
['Home Services', 'Painters'], 
['Home Services', 'Plumbing'], 
['Home Services', 'Pool Cleaners'], 
['Home Services', 'Real Estate'], 
['Home Services', 'Real Estate', 'Apartments'], 
['Home Services', 'Real Estate', 'Commercial Real Estate'], 
['Home Services', 'Real Estate', 'Home Staging'], 
['Home Services', 'Real Estate', 'Mortgage Brokers'], 
['Home Services', 'Real Estate', 'Property Management'], 
['Home Services', 'Real Estate', 'Real Estate Agents'], 
['Home Services', 'Real Estate', 'Real Estate Services'], 
['Home Services', 'Real Estate', 'Shared Office Spaces'], 
['Home Services', 'Real Estate', 'University Housing'], 
['Home Services', 'Roofing'], 
['Home Services', 'Security Systems'], 
['Home Services', 'Shades & Blinds'], 
['Home Services', 'Solar Installation'], 
['Home Services', 'Structural Engineers'], 
['Home Services', 'Television Service Providers'], 
['Home Services', 'Tree Services'], 
['Home Services', 'Utilities'], 
['Home Services', 'Window Washing'], 
['Home Services', 'Windows Installation'], 
['Hotels & Travel', 'Airports'], 
['Hotels & Travel', 'Bed & Breakfast'], 
['Hotels & Travel', 'Campgrounds'], 
['Hotels & Travel', 'Car Rental'], 
['Hotels & Travel', 'Guest Houses'], 
['Hotels & Travel', 'Health Retreats'], 
['Hotels & Travel', 'Hostels'], 
['Hotels & Travel', 'Hotels'], 
['Hotels & Travel', 'Motorcycle Rental'], 
['Hotels & Travel', 'RV Parks'], 
['Hotels & Travel', 'RV Rental'], 
['Hotels & Travel', 'Resorts'], 
['Hotels & Travel', 'Ski Resorts'], 
['Hotels & Travel', 'Tours'], 
['Hotels & Travel', 'Train Stations'], 
['Hotels & Travel', 'Transportation'], 
['Hotels & Travel', 'Transportation', 'Airlines'], 
['Hotels & Travel', 'Transportation', 'Airport Shuttles'], 
['Hotels & Travel', 'Transportation', 'Limos'], 
['Hotels & Travel', 'Transportation', 'Public Transportation'], 
['Hotels & Travel', 'Transportation', 'Taxis'], 
['Hotels & Travel', 'Travel Services'], 
['Hotels & Travel', 'Vacation Rental Agents'], 
['Hotels & Travel', 'Vacation Rentals'], 
['Local Flavor', 'Yelp Events'], 
['Local Services', 'Appliances & Repair'], 
['Local Services', 'Bail Bondsmen'], 
['Local Services', 'Bike Repair/Maintenance'], 
['Local Services', 'Carpet Cleaning'], 
['Local Services', 'Child Care & Day Care'], 
['Local Services', 'Child Care & Day Care', 'ommunity Service/Non-Profit'], 
['Local Services', 'Couriers & Delivery Services'], 
['Local Services', 'Dry Cleaning & Laundry'], 
['Local Services', 'Electronics Repair'], 
['Local Services', 'Funeral Services & Cemeteries'], 
['Local Services', 'Furniture Reupholstery'], 
['Local Services', 'IT Services & Computer Repair'], 
['Local Services', 'IT Services & Computer Repair', 'Data Recovery'], 
['Local Services', 'IT Services & Computer Repair', 'Mobile Phone Repair'], 
['Local Services', 'Jewelry Repair'], 
['Local Services', 'Junk Removal & Hauling'], 
['Local Services', 'Metal Fabricators'], 
['Local Services', 'Nanny Services'], 
['Local Services', 'Notaries'], 
['Local Services', 'Pest Control'], 
['Local Services', 'Printing Services'], 
['Local Services', 'Propane'], 
['Local Services', 'Recording & Rehearsal Studios'], 
['Local Services', 'Recycling Center'], 
['Local Services', 'Screen Printing'], 
['Local Services', 'Screen Printing', 'creen Printing/T-Shirt Printing'], 
['Local Services', 'Self Storage'], 
['Local Services', 'Sewing & Alterations'], 
['Local Services', 'Shipping Centers'], 
['Local Services', 'Shoe Repair'], 
['Local Services', 'Snow Removal'], 
['Local Services', 'Watch Repair'], 
['Mass Media', 'Print Media'], 
['Mass Media', 'Radio Stations'], 
['Mass Media', 'Television Stations'], 
['Nightlife', 'Adult Entertainment'], 
['Nightlife', 'Bars'], 
['Nightlife', 'Bars', 'Champagne Bars'], 
['Nightlife', 'Bars', 'Cocktail Bars'], 
['Nightlife', 'Bars', 'Dive Bars'], 
['Nightlife', 'Bars', 'Gay Bars'], 
['Nightlife', 'Bars', 'Hookah Bars'], 
['Nightlife', 'Bars', 'Lounges'], 
['Nightlife', 'Bars', 'Pubs'], 
['Nightlife', 'Bars', 'Sports Bars'], 
['Nightlife', 'Bars', 'Wine Bars'], 
['Nightlife', 'Comedy Clubs'], 
['Nightlife', 'Country Dance Halls'], 
['Nightlife', 'Dance Clubs'], 
['Nightlife', 'Jazz & Blues'], 
['Nightlife', 'Karaoke'], 
['Nightlife', 'Music Venues'], 
['Nightlife', 'Piano Bars'], 
['Nightlife', 'Pool Halls'], 
['Pets', 'Animal Shelters'], 
['Pets', 'Horse Boarding'], 
['Pets', 'Pet Services'], 
['Pets', 'Pet Services', 'Dog Walkers'], 
['Pets', 'Pet Services', 'Pet Boarding/Pet Sitting'], 
['Pets', 'Pet Services', 'Pet Groomers'], 
['Pets', 'Pet Services', 'Pet Training'], 
['Pets', 'Pet Stores'], 
['Pets', 'Veterinarians'], 
['Professional Services', 'Accountants'], 
['Professional Services', 'Advertising'], 
['Professional Services', 'Architects'], 
['Professional Services', 'Boat Repair'], 
['Professional Services', 'Career Counseling'], 
['Professional Services', 'Editorial Services'], 
['Professional Services', 'Employment Agencies'], 
['Professional Services', 'Graphic Design'], 
['Professional Services', 'Internet Service Providers'], 
['Professional Services', 'Lawyers'], 
['Professional Services', 'Lawyers', 'Bankruptcy Law'], 
['Professional Services', 'Lawyers', 'Business Law'], 
['Professional Services', 'Lawyers', 'Criminal Defense Law'], 
['Professional Services', 'Lawyers', 'DUI Law'], 
['Professional Services', 'Lawyers', 'Divorce & Family Law'], 
['Professional Services', 'Lawyers', 'Employment Law'], 
['Professional Services', 'Lawyers', 'Estate Planning Law'], 
['Professional Services', 'Lawyers', 'General Litigation'], 
['Professional Services', 'Lawyers', 'Immigration Law'], 
['Professional Services', 'Lawyers', 'Personal Injury Law'], 
['Professional Services', 'Lawyers', 'Real Estate Law'], 
['Professional Services', 'Legal Services'], 
['Professional Services', 'Life Coach'], 
['Professional Services', 'Marketing'], 
['Professional Services', 'Matchmakers'], 
['Professional Services', 'Office Cleaning'], 
['Professional Services', 'Payroll Services'], 
['Professional Services', 'Personal Assistants'], 
['Professional Services', 'Private Investigation'], 
['Professional Services', 'Public Relations'], 
['Professional Services', 'Signmaking'], 
['Professional Services', 'Talent Agencies'], 
['Professional Services', 'Taxidermy'], 
['Professional Services', 'Translation Services'], 
['Professional Services', 'Video/Film Production'], 
['Professional Services', 'Web Design'], 
['Public Services & Government', 'Courthouses'], 
['Public Services & Government', 'Departments of Motor Vehicles'], 
['Public Services & Government', 'Embassy'], 
['Public Services & Government', 'Fire Departments'], 
['Public Services & Government', 'Landmarks & Historical Buildings'], 
['Public Services & Government', 'Libraries'], 
['Public Services & Government', 'Police Departments'], 
['Public Services & Government', 'Post Offices'], 
['Real Estate', 'Apartments'], 
['Real Estate', 'Commercial Real Estate'], 
['Real Estate', 'Home Staging'], 
['Real Estate', 'Mortgage Brokers'], 
['Real Estate', 'Property Management'], 
['Real Estate', 'Real Estate Agents'], 
['Real Estate', 'Real Estate Services'], 
['Real Estate', 'Shared Office Spaces'], 
['Real Estate', 'University Housing'], 
['Religious Organizations', 'Buddhist Temples'], 
['Religious Organizations', 'Churches'], 
['Religious Organizations', 'Hindu Temples'], 
['Religious Organizations', 'Mosques'], 
['Religious Organizations', 'Synagogues'], 
['Restaurants', 'Afghan'], 
['Restaurants', 'African'], 
['Restaurants', 'African', 'Senegalese'], 
['Restaurants', 'African', 'South African'], 
['Restaurants', 'American (New)'], 
['Restaurants', 'American (Traditional)'], 
['Restaurants', 'Arabian'], 
['Restaurants', 'Argentine'], 
['Restaurants', 'Armenian'], 
['Restaurants', 'Asian Fusion'], 
['Restaurants', 'Australian'], 
['Restaurants', 'Austrian'], 
['Restaurants', 'Bangladeshi'], 
['Restaurants', 'Barbeque'], 
['Restaurants', 'Basque'], 
['Restaurants', 'Belgian'], 
['Restaurants', 'Brasseries'], 
['Restaurants', 'Brazilian'], 
['Restaurants', 'Breakfast & Brunch'], 
['Restaurants', 'British'], 
['Restaurants', 'Buffets'], 
['Restaurants', 'Burgers'], 
['Restaurants', 'Burmese'], 
['Restaurants', 'Cafes'], 
['Restaurants', 'Cafeteria'], 
['Restaurants', 'Cajun/Creole'], 
['Restaurants', 'Cambodian'], 
['Restaurants', 'Caribbean'], 
['Restaurants', 'Caribbean', 'Dominican'], 
['Restaurants', 'Caribbean', 'Haitian'], 
['Restaurants', 'Caribbean', 'Puerto Rican'], 
['Restaurants', 'Caribbean', 'Trinidadian'], 
['Restaurants', 'Catalan'], 
['Restaurants', 'Cheesesteaks'], 
['Restaurants', 'Chicken Wings'], 
['Restaurants', 'Chinese'], 
['Restaurants', 'Chinese', 'Cantonese'], 
['Restaurants', 'Chinese', 'Dim Sum'], 
['Restaurants', 'Chinese', 'Shanghainese'], 
['Restaurants', 'Chinese', 'Szechuan'], 
['Restaurants', 'Comfort Food'], 
['Restaurants', 'Creperies'], 
['Restaurants', 'Cuban'], 
['Restaurants', 'Czech'], 
['Restaurants', 'Delis'], 
['Restaurants', 'Diners'], 
['Restaurants', 'Ethiopian'], 
['Restaurants', 'Fast Food'], 
['Restaurants', 'Filipino'], 
['Restaurants', 'Fish & Chips'], 
['Restaurants', 'Fondue'], 
['Restaurants', 'Food Court'], 
['Restaurants', 'Food Stands'], 
['Restaurants', 'French'], 
['Restaurants', 'Gastropubs'], 
['Restaurants', 'German'], 
['Restaurants', 'Gluten-Free'], 
['Restaurants', 'Greek'], 
['Restaurants', 'Halal'], 
['Restaurants', 'Hawaiian'], 
['Restaurants', 'Himalayan/Nepalese'], 
['Restaurants', 'Hot Dogs'], 
['Restaurants', 'Hot Pot'], 
['Restaurants', 'Hungarian'], 
['Restaurants', 'Iberian'], 
['Restaurants', 'Indian'], 
['Restaurants', 'Indonesian'], 
['Restaurants', 'Irish'], 
['Restaurants', 'Italian'], 
['Restaurants', 'Japanese'], 
['Restaurants', 'Korean'], 
['Restaurants', 'Kosher'], 
['Restaurants', 'Laotian'], 
['Restaurants', 'Latin American'], 
['Restaurants', 'Latin American', 'Colombian'], 
['Restaurants', 'Latin American', 'Salvadoran'], 
['Restaurants', 'Latin American', 'Venezuelan'], 
['Restaurants', 'Live/Raw Food'], 
['Restaurants', 'Malaysian'], 
['Restaurants', 'Mediterranean'], 
['Restaurants', 'Mediterranean', 'Falafel'], 
['Restaurants', 'Mexican'], 
['Restaurants', 'Middle Eastern'], 
['Restaurants', 'Middle Eastern', 'Egyptian'], 
['Restaurants', 'Middle Eastern', 'Lebanese'], 
['Restaurants', 'Modern European'], 
['Restaurants', 'Mongolian'], 
['Restaurants', 'Moroccan'], 
['Restaurants', 'Pakistani'], 
['Restaurants', 'Persian/Iranian'], 
['Restaurants', 'Peruvian'], 
['Restaurants', 'Pizza'], 
['Restaurants', 'Polish'], 
['Restaurants', 'Portuguese'], 
['Restaurants', 'Russian'], 
['Restaurants', 'Salad'], 
['Restaurants', 'Sandwiches'], 
['Restaurants', 'Scandinavian'], 
['Restaurants', 'Scottish'], 
['Restaurants', 'Seafood'], 
['Restaurants', 'Singaporean'], 
['Restaurants', 'Slovakian'], 
['Restaurants', 'Soul Food'], 
['Restaurants', 'Soup'], 
['Restaurants', 'Southern'], 
['Restaurants', 'Spanish'], 
['Restaurants', 'Steakhouses'], 
['Restaurants', 'Sushi Bars'], 
['Restaurants', 'Taiwanese'], 
['Restaurants', 'Tapas Bars'], 
['Restaurants', 'Tapas/Small Plates'], 
['Restaurants', 'Tapas/Small Plates', 'Lebanese'], 
['Restaurants', 'Tex-Mex'], 
['Restaurants', 'Thai'], 
['Restaurants', 'Turkish'], 
['Restaurants', 'Ukrainian'], 
['Restaurants', 'Vegan'], 
['Restaurants', 'Vegetarian'], 
['Restaurants', 'Vietnamese'], 
['Shopping', 'Adult'], 
['Shopping', 'Antiques'], 
['Shopping', 'Art Galleries'], 
['Shopping', 'Arts & Crafts'], 
['Shopping', 'Arts & Crafts', 'Art Supplies'], 
['Shopping', 'Arts & Crafts', 'Cards & Stationery'], 
['Shopping', 'Arts & Crafts', 'Costumes'], 
['Shopping', 'Arts & Crafts', 'Embroidery & Crochet'], 
['Shopping', 'Arts & Crafts', 'Fabric Stores'], 
['Shopping', 'Arts & Crafts', 'Framing'], 
['Shopping', 'Auction Houses'], 
['Shopping', 'Baby Gear & Furniture'], 
['Shopping', 'Bespoke Clothing'], 
['Shopping', 'Books, Mags, Music & Video'], 
['Shopping', 'Books, Mags, Music & Video', 'Bookstores'], 
['Shopping', 'Books, Mags, Music & Video', 'Comic Books'], 
['Shopping', 'Books, Mags, Music & Video', 'Music & DVDs'], 
['Shopping', 'Books, Mags, Music & Video', 'Newspapers & Magazines'], 
['Shopping', 'Books, Mags, Music & Video', 'Videos & Video Game Rental'], 
['Shopping', 'Books, Mags, Music & Video', 'Vinyl Records'], 
['Shopping', 'Bridal'], 
['Shopping', 'Computers'], 
['Shopping', 'Cosmetics & Beauty Supply'], 
['Shopping', 'Department Stores'], 
['Shopping', 'Discount Store'], 
['Shopping', 'Drugstores'], 
['Shopping', 'Electronics'], 
['Shopping', 'Eyewear & Opticians'], 
['Shopping', 'Fashion'], 
['Shopping', 'Fashion', 'Accessories'], 
['Shopping', 'Fashion', "Children's Clothing"], 
['Shopping', 'Fashion', 'Department Stores'], 
['Shopping', 'Fashion', 'Formal Wear'], 
['Shopping', 'Fashion', 'Hats'], 
['Shopping', 'Fashion', 'Leather Goods'], 
['Shopping', 'Fashion', 'Lingerie'], 
['Shopping', 'Fashion', 'Maternity Wear'], 
['Shopping', 'Fashion', "Men's Clothing"], 
['Shopping', 'Fashion', 'Plus Size Fashion'], 
['Shopping', 'Fashion', 'Shoe Stores'], 
['Shopping', 'Fashion', 'Sports Wear'], 
['Shopping', 'Fashion', 'Surf Shop'], 
['Shopping', 'Fashion', 'Swimwear'], 
['Shopping', 'Fashion', 'Used, Vintage & Consignment'], 
['Shopping', 'Fashion', "Women's Clothing"], 
['Shopping', 'Fireworks'], 
['Shopping', 'Flea Markets'], 
['Shopping', 'Flowers & Gifts'], 
['Shopping', 'Flowers & Gifts', 'Cards & Stationery'], 
['Shopping', 'Flowers & Gifts', 'Florists'], 
['Shopping', 'Flowers & Gifts', 'Gift Shops'], 
['Shopping', 'Gold Buyers'], 
['Shopping', 'Golf Equipment Shops'], 
['Shopping', 'Guns & Ammo'], 
['Shopping', 'Hobby Shops'], 
['Shopping', 'Home & Garden'], 
['Shopping', 'Home & Garden', 'Appliances'], 
['Shopping', 'Home & Garden', 'Furniture Stores'], 
['Shopping', 'Home & Garden', 'Hardware Stores'], 
['Shopping', 'Home & Garden', 'Home Decor'], 
['Shopping', 'Home & Garden', 'Hot Tub & Pool'], 
['Shopping', 'Home & Garden', 'Kitchen & Bath'], 
['Shopping', 'Home & Garden', 'Mattresses'], 
['Shopping', 'Home & Garden', 'Nurseries & Gardening'], 
['Shopping', 'Home & Garden', 'Rugs'], 
['Shopping', 'Jewelry'], 
['Shopping', 'Knitting Supplies'], 
['Shopping', 'Luggage'], 
['Shopping', 'Medical Supplies'], 
['Shopping', 'Mobile Phones'], 
['Shopping', 'Motorcycle Gear'], 
['Shopping', 'Musical Instruments & Teachers'], 
['Shopping', 'Office Equipment'], 
['Shopping', 'Outlet Stores'], 
['Shopping', 'Pawn Shops'], 
['Shopping', 'Personal Shopping'], 
['Shopping', 'Photography Stores & Services'], 
['Shopping', 'Pool & Billiards'], 
['Shopping', 'Pool & Billiards', 'op-up Shops'], 
['Shopping', 'Shopping Centers'], 
['Shopping', 'Sporting Goods'], 
['Shopping', 'Sporting Goods', 'Bikes'], 
['Shopping', 'Sporting Goods', 'Golf Equipment'], 
['Shopping', 'Sporting Goods', 'Outdoor Gear'], 
['Shopping', 'Sporting Goods', 'Sports Wear'], 
['Shopping', 'Thrift Stores'], 
['Shopping', 'Tobacco Shops'], 
['Shopping', 'Toy Stores'], 
['Shopping', 'Trophy Shops'], 
['Shopping', 'Uniforms'], 
['Shopping', 'Watches'], 
['Shopping', 'Wholesale Stores'], 
['Shopping', 'Wigs']]

function createCategoryTable(db) {
	db.transaction(function (tx) {
		var QUERY = "CREATE TABLE Category (" +
		"	cat_id INT PRIMARY KEY NOT NULL," +
		"	level0 VARCHAR(40) NOT NULL," +
		"	level1 VARCHAR(40) NOT NULL," +
		"	level2 VARCHAR(40)" +
		");"
		tx.executeSql(QUERY);
	});
}

function insertCategoryData(db) {
	QUERY = []
	for (var i = 0; i < category.length; i++) {
		QUERY.push(makeCatInsertQuery(category[i], i))
	}

	db.transaction(function (tx) {
		for (var i = 0; i < category.length; i++) {
			var q = QUERY[i]
			tx.executeSql(q, [], null, fail);
			var fail = function(tx, error) {
				console.log(i + error.message + q)
			} 
		}
	});

}

function makeCatInsertQuery(list, n) {

	var handleApostrophe = function(string) {
		if (typeof string != "string") return string;
		splited = string.split("'")
		edited = splited.join("''")
		return edited
	}

	var QUERY = "INSERT OR REPLACE INTO Category (cat_id, "
	for (var i = 0; i < list.length; i++) {
		QUERY += "level" + i + ", "
	}
	QUERY = QUERY.substr(0, QUERY.length-2) + ") "
	
	QUERY += "VALUES (" + n + ", "
	for (var i = 0; i < list.length; i++) {
		list[i] = handleApostrophe(list[i])
		QUERY += "'" + list[i] + "', "
	}
	QUERY = QUERY.substr(0, QUERY.length-2) + ");"

	return QUERY
}